# Generated by Django 4.0.3 on 2022-03-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=40, unique=True)),
                ('hashpassword', models.CharField(default='', max_length=100)),
                ('salt', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
