# Generated by Django 4.0.3 on 2022-03-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTable',
            new_name='UserCustom',
        ),
    ]
