# Generated by Django 4.0.3 on 2022-03-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertable',
            table='UserTable',
        ),
    ]
