# Generated by Django 4.0.3 on 2022-03-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usertable_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='hashpassword',
            new_name='password',
        ),
    ]
