# Generated by Django 4.0.3 on 2022-03-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_hashpassword_usertable_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='salt',
        ),
    ]
