# Generated by Django 4.0.3 on 2022-03-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_usertable_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='salt',
            field=models.CharField(default='', max_length=40),
        ),
    ]
