# Generated by Django 4.0.3 on 2022-03-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usercustom_table'),
        ('authentication', '0005_usertable_salt'),
    ]

    operations = [
    ]
