# Generated by Django 4.0.3 on 2022-03-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_0003_alter_usercustom_table_0005_usertable_salt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustom',
            new_name='UserTable',
        ),
        migrations.AlterModelTable(
            name='usertable',
            table='UserTable',
        ),
    ]
