# Generated by Django 4.0.3 on 2022-03-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_usercustom_usertable_alter_usertable_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertable',
            table='UserCustom',
        ),
    ]
