# Generated by Django 4.0.3 on 2022-03-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_usertable_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTable',
            new_name='UserCustom',
        ),
    ]
